### PR TITLE
Support Python 3 in addition to Python 2.

### PR DESCRIPTION
**Pull request by mahiuchun**
As requested.

### CODE REVIEW

**Comment by imirkin** [comment]
This looks great! I'm going to leave it up for a couple of days in case there's additional feedback, but this looks good. I'm also going to triple-check that the generated files remain the same with py2 and py3.

**Comment by imirkin** [comment]
I expect there are minor conflicts with my fix due to my changing a print line. Could you update this?

**Comment by mahiuchun** [comment]
Updated

**Comment by mahiuchun** [comment]
ping?

**Pull request merged**
